# Detectron2 Configuration File

# Output directory
OUTPUT_DIR: "../models/Detectron2_Models"

# Model configuration from COCO dataset
MODEL:
  WEIGHTS: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256  # Number of proposals to be processed per image
    NUM_CLASSES: 1  # Change this to match your dataset (1 class for your case)
  MASK_ON: true  # Enable mask prediction if using Mask R-CNN

# Dataset settings
DATASETS:
  TRAIN: ("my_dataset_val",)  # Replace with your training dataset name
  TEST: ()  # Set to your testing dataset name if available

# Dataloader settings
DATALOADER:
  NUM_WORKERS: 2  # Number of worker threads for loading data

# Solver settings
SOLVER:
  IMS_PER_BATCH: 2  # Images per batch
  BASE_LR: 0.00025  # Base learning rate
  MAX_ITER: 1000  # Maximum number of iterations
  STEPS: []  # Steps to decrease learning rate (optional)

# Miscellaneous settings
INPUT:
  MIN_SIZE_TRAIN: (800,)  # Minimum size for training images
  MIN_SIZE_TEST: 800  # Minimum size for testing images
  MAX_SIZE: 1333  # Maximum size for images
